package com.example.valtrak.CardData.Nations.Information;

import lombok.AllArgsConstructor;
import lombok.Getter;


@Getter
@AllArgsConstructor
public enum Nations {

    /*======================================== NATIONS ========================================*/

    AFGHANISTAN("Afghanistan", "AFG"),
    ALBANIA("Albania", "ALB"),
    ALGERIA("Algeria", "DZA"),
    ANDORRA("Andorra", "AND"),
    ANGOLA("Angola", "AGO"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "ATG"),
    ARGENTINA("Argentina", "ARG"),
    ARMENIA("Armenia", "ARM"),
    AUSTRALIA("Australia", "AUS"),
    AUSTRIA("Austria", "AUT"),
    AZERBAIJAN("Azerbaijan", "AZE"),
    BAHAMAS("Bahamas", "BHS"),
    BAHRAIN("Bahrain", "BHR"),
    BANGLADESH("Bangladesh", "BGD"),
    BARBADOS("Barbados", "BRB"),
    BELARUS("Belarus", "BLR"),
    BELGIUM("Belgium", "BEL"),
    BELIZE("Belize", "BLZ"),
    BENIN("Benin", "BEN"),
    BHUTAN("Bhutan", "BTN"),
    BOLIVIA("Bolivia", "BOL"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "BIH"),
    BOTSWANA("Botswana", "BWA"),
    BRAZIL("Brazil", "BRA"),
    BRUNEI("Brunei", "BRN"),
    BULGARIA("Bulgaria", "BGR"),
    BURKINA_FASO("Burkina Faso", "BFA"),
    BURUNDI("Burundi", "BDI"),
    CABO_VERDE("Cabo Verde", "CPV"),
    CAMBODIA("Cambodia", "KHM"),
    CAMEROON("Cameroon", "CMR"),
    CANADA("Canada", "CAN"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "CAF"),
    CHAD("Chad", "TCD"),
    CHILE("Chile", "CHL"),
    CHINA("China", "CHN"),
    COLOMBIA("Colombia", "COL"),
    COMOROS("Comoros", "COM"),
    CONGO("Congo", "COG"),
    COSTA_RICA("Costa Rica", "CRI"),
    CROATIA("Croatia", "HRV"),
    CUBA("Cuba", "CUB"),
    CYPRUS("Cyprus", "CYP"),
    CZECH_REPUBLIC("Czech Republic", "CZE"),
    DENMARK("Denmark", "DNK"),
    DJIBOUTI("Djibouti", "DJI"),
    DOMINICA("Dominica", "DMA"),
    DOMINICAN_REPUBLIC("Dominican Republic", "DOM"),
    ECUADOR("Ecuador", "ECU"),
    EGYPT("Egypt", "EGY"),
    EL_SALVADOR("El Salvador", "SLV"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "GNQ"),
    ERITREA("Eritrea", "ERI"),
    ESTONIA("Estonia", "EST"),
    ESWATINI("Eswatini", "SWZ"),
    ETHIOPIA("Ethiopia", "ETH"),
    FIJI("Fiji", "FJI"),
    FINLAND("Finland", "FIN"),
    FRANCE("France", "FRA"),
    GABON("Gabon", "GAB"),
    GAMBIA("Gambia", "GMB"),
    GEORGIA("Georgia", "GEO"),
    GERMANY("Germany", "DEU"),
    GHANA("Ghana", "GHA"),
    GREECE("Greece", "GRC"),
    GRENADA("Grenada", "GRD"),
    GUATEMALA("Guatemala", "GTM"),
    GUINEA("Guinea", "GIN"),
    GUINEA_BISSAU("Guinea-Bissau", "GNB"),
    GUYANA("Guyana", "GUY"),
    HAITI("Haiti", "HTI"),
    HONDURAS("Honduras", "HND"),
    HUNGARY("Hungary", "HUN"),
    ICELAND("Iceland", "ISL"),
    INDIA("India", "IND"),
    INDONESIA("Indonesia", "IDN"),
    IRAN("Iran", "IRN"),
    IRAQ("Iraq", "IRQ"),
    IRELAND("Ireland", "IRL"),
    ISRAEL("Israel", "ISR"),
    ITALY("Italy", "ITA"),
    JAMAICA("Jamaica", "JAM"),
    JAPAN("Japan", "JPN"),
    JORDAN("Jordan", "JOR"),
    KAZAKHSTAN("Kazakhstan", "KAZ"),
    KENYA("Kenya", "KEN"),
    KIRIBATI("Kiribati", "KIR"),
    KOSOVO("Kosovo", "XKX"),
    KUWAIT("Kuwait", "KWT"),
    KYRGYZSTAN("Kyrgyzstan", "KGZ"),
    LAOS("Laos", "LAO"),
    LATVIA("Latvia", "LVA"),
    LEBANON("Lebanon", "LBN"),
    LESOTHO("Lesotho", "LSO"),
    LIBERIA("Liberia", "LBR"),
    LIBYA("Libya", "LBY"),
    LIECHTENSTEIN("Liechtenstein", "LIE"),
    LITHUANIA("Lithuania", "LTU"),
    LUXEMBOURG("Luxembourg", "LUX"),
    MADAGASCAR("Madagascar", "MDG"),
    MALAWI("Malawi", "MWI"),
    MALAYSIA("Malaysia", "MYS"),
    MALDIVES("Maldives", "MDV"),
    MALI("Mali", "MLI"),
    MALTA("Malta", "MLT"),
    MARSHALL_ISLANDS("Marshall Islands", "MHL"),
    MAURITANIA("Mauritania", "MRT"),
    MAURITIUS("Mauritius", "MUS"),
    MEXICO("Mexico", "MEX"),
    MICRONESIA("Micronesia", "FSM"),
    MOLDOVA("Moldova", "MDA"),
    MONACO("Monaco", "MCO"),
    MONGOLIA("Mongolia", "MNG"),
    MONTENEGRO("Montenegro", "MNE"),
    MOROCCO("Morocco", "MAR"),
    MOZAMBIQUE("Mozambique", "MOZ"),
    MYANMAR("Myanmar", "MMR"),
    NAMIBIA("Namibia", "NAM"),
    NAURU("Nauru", "NRU"),
    NEPAL("Nepal", "NPL"),
    NETHERLANDS("Netherlands", "NLD"),
    NEW_ZEALAND("New Zealand", "NZL"),
    NICARAGUA("Nicaragua", "NIC"),
    NIGER("Niger", "NER"),
    NIGERIA("Nigeria", "NGA"),
    NORTH_KOREA("North Korea", "PRK"),
    NORTH_MACEDONIA("North Macedonia", "MKD"),
    NORWAY("Norway", "NOR"),
    OMAN("Oman", "OMN"),
    PAKISTAN("Pakistan", "PAK"),
    PALAU("Palau", "PLW"),
    PALESTINE("Palestine", "PSE"),
    PANAMA("Panama", "PAN"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "PNG"),
    PARAGUAY("Paraguay", "PRY"),
    PERU("Peru", "PER"),
    PHILIPPINES("Philippines", "PHL"),
    POLAND("Poland", "POL"),
    PORTUGAL("Portugal", "PRT"),
    QATAR("Qatar", "QAT"),
    ROMANIA("Romania", "ROU"),
    RUSSIA("Russia", "RUS"),
    RWANDA("Rwanda", "RWA"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "KNA"),
    SAINT_LUCIA("Saint Lucia", "LCA"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "VCT"),
    SAMOA("Samoa", "WSM"),
    SAN_MARINO("San Marino", "SMR"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "STP"),
    SAUDI_ARABIA("Saudi Arabia", "SAU"),
    SENEGAL("Senegal", "SEN"),
    SERBIA("Serbia", "SRB"),
    SEYCHELLES("Seychelles", "SYC"),
    SIERRA_LEONE("Sierra Leone", "SLE"),
    SINGAPORE("Singapore", "SGP"),
    SLOVAKIA("Slovakia", "SVK"),
    SLOVENIA("Slovenia", "SVN"),
    SOLOMON_ISLANDS("Solomon Islands", "SLB"),
    SOMALIA("Somalia", "SOM"),
    SOUTH_AFRICA("South Africa", "ZAF"),
    SOUTH_KOREA("South Korea", "KOR"),
    SOUTH_SUDAN("South Sudan", "SSD"),
    SPAIN("Spain", "ESP"),
    SRI_LANKA("Sri Lanka", "LKA"),
    SUDAN("Sudan", "SDN"),
    SURINAME("Suriname", "SUR"),
    SWEDEN("Sweden", "SWE"),
    SWITZERLAND("Switzerland", "CHE"),
    SYRIA("Syria", "SYR"),
    TAIWAN("Taiwan", "TWN"),
    TAJIKISTAN("Tajikistan", "TJK"),
    TANZANIA("Tanzania", "TZA"),
    THAILAND("Thailand", "THA"),
    TIMOR_LESTE("Timor-Leste", "TLS"),
    TOGO("Togo", "TGO"),
    TONGA("Tonga", "TON"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "TTO"),
    TUNISIA("Tunisia", "TUN"),
    TURKEY("Turkey", "TUR"),
    TURKMENISTAN("Turkmenistan", "TKM"),
    TUVALU("Tuvalu", "TUV"),
    UGANDA("Uganda", "UGA"),
    UKRAINE("Ukraine", "UKR"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "ARE"),
    UNITED_KINGDOM("United Kingdom", "GBR"),
    UNITED_STATES("United States", "USA"),
    URUGUAY("Uruguay", "URY"),
    UZBEKISTAN("Uzbekistan", "UZB"),
    VANUATU("Vanuatu", "VUT"),
    VATICAN_CITY("Vatican City", "VAT"),
    VENEZUELA("Venezuela", "VEN"),
    VIETNAM("Vietnam", "VNM"),
    YEMEN("Yemen", "YEM"),
    ZAMBIA("Zambia", "ZMB"),
    ZIMBABWE("Zimbabwe", "ZWE");

    /*=========================================================================================*/

    private final String name;
    private final String abbreviation;

}